services:
  - type: web
    name: the-tweety
    env: python
    plan: free
    rootDir: shopify
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn shopify.wsgi:application --log-file -"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "the-tweety.onrender.com"
      - key: DATABASE_URL
        sync: false
