services:
  - type: web
    name: the-tweety
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn shopify.wsgi:application --log-file -"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "the-tweety.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: the-tweety-db
          property: connectionString

databases:
  - name: the-tweety-db
    plan: free
    databaseName: thetweety
    user: thetweety
